name: planext4u_rider
description: Planext4u rider application.
publish_to: 'none'
version: 0.1.0+1

resolution: workspace

environment:
  sdk: ^3.11.1

dependencies:
  firebase_auth: ^6.6.1
  firebase_core: ^4.14.0
  flutter:
    sdk: flutter
  geolocator: ^14.0.3
  image_picker: ^1.2.3
  planext4u_api_client: ^0.1.0
  planext4u_config: ^0.1.0
  planext4u_core: ^0.1.0
  planext4u_design_system: ^0.1.0
  planext4u_experience: ^0.1.0
  planext4u_identity: ^0.1.0
  planext4u_observability: ^0.1.0
  planext4u_storage: ^0.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
