#!/usr/bin/env ruby
# frozen_string_literal: true

require 'base64'
require 'fileutils'

begin
  require 'xcodeproj'
rescue LoadError
  # Homebrew CocoaPods keeps its gems in an isolated libexec. Reuse the
  # already-installed xcodeproj there without modifying the host Ruby setup.
  gem_libs = [
    '/opt/homebrew/Cellar/cocoapods/*/libexec/gems/*/lib',
    '/usr/local/Cellar/cocoapods/*/libexec/gems/*/lib'
  ].flat_map { |pattern| Dir[pattern] }
  $LOAD_PATH.unshift(*gem_libs)
  require 'xcodeproj'
end

ROOT = File.expand_path('..', __dir__)
APPS = {
  'customer' => {
    bundle_id: 'net.planext4u.customer',
    display_name: 'Planext4u Customer',
    path_prefix: '/app'
  },
  'vendor' => {
    bundle_id: 'net.planext4u.vendor',
    display_name: 'Planext4u Vendor',
    path_prefix: '/vendor'
  },
  'rider' => {
    bundle_id: 'net.planext4u.rider',
    display_name: 'Planext4u Rider',
    path_prefix: '/rider'
  }
}.freeze
FLAVORS = {
  'development' => {
    identifier_suffix: '.dev',
    display_suffix: ' Dev',
    host: 'dev.planext4u.net',
    scheme_suffix: '-dev'
  },
  'staging' => {
    identifier_suffix: '.staging',
    display_suffix: ' Staging',
    host: 'staging.planext4u.net',
    scheme_suffix: '-staging'
  },
  'production' => {
    identifier_suffix: '',
    display_suffix: '',
    host: 'planext4u.net',
    scheme_suffix: ''
  }
}.freeze
MODES = {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release
}.freeze
IOS_DEPLOYMENT_TARGET = '15.0'

def deep_copy(value)
  Marshal.load(Marshal.dump(value))
end

def write_xcconfig(app_dir, app_name, app, flavor_name, flavor, mode)
  base_config = mode == 'Debug' ? 'Debug.xcconfig' : 'Release.xcconfig'
  dart_define = Base64.strict_encode64("APP_ENV=#{flavor_name}")
  contents = <<~CONFIG
    // Generated by tool/configure_ios_flavors.rb. Do not edit by hand.
    #include "#{base_config}"
    APP_ENV = #{flavor_name}
    APP_DISPLAY_NAME = #{app[:display_name]}#{flavor[:display_suffix]}
    PRODUCT_BUNDLE_IDENTIFIER = #{app[:bundle_id]}#{flavor[:identifier_suffix]}
    DEEPLINK_HOST = #{flavor[:host]}
    DEEPLINK_SCHEME = planext4u-#{app_name}#{flavor[:scheme_suffix]}
    DEEPLINK_PATH_PREFIX = #{app[:path_prefix]}
    APS_ENVIRONMENT = #{flavor_name == 'production' ? 'production' : 'development'}
    DART_DEFINES = $(inherited),#{dart_define}
  CONFIG
  path = File.join(app_dir, 'ios', 'Flutter', "#{mode}-#{flavor_name}.xcconfig")
  File.write(path, contents)
end

def preserve_flutter_scheme_configuration(scheme_path, runner_uuid, prepare_framework:)
  contents = File.read(scheme_path)
  marker = '      customLLDBInitFile = "$(SRCROOT)/Flutter/ephemeral/flutter_lldbinit"'
  contents = contents.gsub(
    /(selectedLauncherIdentifier = "Xcode\.DebuggerFoundation\.Launcher\.LLDB"\n)(      (?:shouldUseLaunchSchemeArgsEnv|launchStyle) = )/,
    "\\1#{marker}\n\\2"
  )
  if prepare_framework
    contents = contents.gsub(
      /^[ \t]*<PreActions>\n.*?Run Prepare Flutter Framework Script.*?^[ \t]*<\/PreActions>\n/m,
      ''
    )
    pre_action = <<~XML.chomp
      <PreActions>
         <ExecutionAction
            ActionType = "Xcode.IDEStandardExecutionActionsCore.ExecutionActionType.ShellScriptAction">
            <ActionContent
               title = "Run Prepare Flutter Framework Script"
               scriptText = "/bin/sh &quot;$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh&quot; prepare&#10;">
               <EnvironmentBuildable>
                  <BuildableReference
                     BuildableIdentifier = "primary"
                     BlueprintIdentifier = "#{runner_uuid}"
                     BuildableName = "Runner.app"
                     BlueprintName = "Runner"
                     ReferencedContainer = "container:Runner.xcodeproj">
                  </BuildableReference>
               </EnvironmentBuildable>
            </ActionContent>
         </ExecutionAction>
      </PreActions>
    XML
    pre_action = pre_action.lines.map { |line| "      #{line}" }.join.chomp
    contents = contents.sub(/(<BuildAction\n(?:[^>]*\n)*?[^>]*>\n)/, "\\1#{pre_action}\n")
  end
  File.write(scheme_path, contents)
end

APPS.each do |app_name, app|
  app_dir = File.join(ROOT, 'apps', app_name)
  project_path = File.join(app_dir, 'ios', 'Runner.xcodeproj')
  project = Xcodeproj::Project.open(project_path)
  runner = project.targets.find { |target| target.name == 'Runner' }
  runner_tests = project.targets.find { |target| target.name == 'RunnerTests' }
  raise "Runner target missing in #{project_path}" unless runner
  raise "RunnerTests target missing in #{project_path}" unless runner_tests

  project.build_configurations.each do |configuration|
    configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_DEPLOYMENT_TARGET
  end
  [runner, runner_tests].each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_DEPLOYMENT_TARGET
    end
  end

  flutter_group = project.main_group.find_subpath('Flutter', true)

  FLAVORS.each do |flavor_name, flavor|
    MODES.each do |mode, type|
      configuration_name = "#{mode}-#{flavor_name}"
      source_project_config = project.build_configurations.find { |config| config.name == mode }
      source_target_config = runner.build_configurations.find { |config| config.name == mode }
      source_test_config = runner_tests.build_configurations.find { |config| config.name == mode }
      unless source_project_config && source_target_config && source_test_config
        raise "Source #{mode} configuration missing in #{project_path}"
      end

      write_xcconfig(app_dir, app_name, app, flavor_name, flavor, mode)
      config_filename = "#{configuration_name}.xcconfig"
      file_reference = flutter_group.files.find do |file|
        file.path == config_filename || file.path == "Flutter/#{config_filename}"
      end
      file_reference ||= flutter_group.new_file("Flutter/#{config_filename}")
      file_reference.name = config_filename
      file_reference.path = "Flutter/#{config_filename}"

      project_config = project.add_build_configuration(configuration_name, type)
      project_config.build_settings = deep_copy(source_project_config.build_settings)
      project_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_DEPLOYMENT_TARGET

      target_config = runner.add_build_configuration(configuration_name, type)
      target_config.build_settings = deep_copy(source_target_config.build_settings)
      target_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_DEPLOYMENT_TARGET
      target_config.base_configuration_reference = file_reference
      target_config.build_settings['APP_DISPLAY_NAME'] = "#{app[:display_name]}#{flavor[:display_suffix]}"
      target_config.build_settings['CODE_SIGN_ENTITLEMENTS'] = 'Runner/Runner.entitlements'
      target_config.build_settings['DEEPLINK_HOST'] = flavor[:host]
      target_config.build_settings['DEEPLINK_PATH_PREFIX'] = app[:path_prefix]
      target_config.build_settings['DEEPLINK_SCHEME'] = "planext4u-#{app_name}#{flavor[:scheme_suffix]}"
      target_config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = "#{app[:bundle_id]}#{flavor[:identifier_suffix]}"
      target_config.build_settings['APS_ENVIRONMENT'] = flavor_name == 'production' ? 'production' : 'development'

      test_config = runner_tests.add_build_configuration(configuration_name, type)
      test_config.build_settings = deep_copy(source_test_config.build_settings)
      test_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_DEPLOYMENT_TARGET
      test_config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = "#{app[:bundle_id]}#{flavor[:identifier_suffix]}.RunnerTests"
      test_config.build_settings['SWIFT_VERSION'] = '5.0'
    end

    scheme = Xcodeproj::XCScheme.new
    scheme.add_build_target(runner)
    scheme.add_test_target(runner_tests)
    scheme.set_launch_target(runner)
    scheme.test_action.build_configuration = "Debug-#{flavor_name}"
    scheme.launch_action.build_configuration = "Debug-#{flavor_name}"
    scheme.profile_action.build_configuration = "Profile-#{flavor_name}"
    scheme.analyze_action.build_configuration = "Debug-#{flavor_name}"
    scheme.archive_action.build_configuration = "Release-#{flavor_name}"
    scheme.save_as(project_path, flavor_name, true)
    preserve_flutter_scheme_configuration(
      File.join(project_path, 'xcshareddata', 'xcschemes', "#{flavor_name}.xcscheme"),
      runner.uuid,
      prepare_framework: app_name == 'customer'
    )
  end

  runner_scheme_path = File.join(project_path, 'xcshareddata', 'xcschemes', 'Runner.xcscheme')
  if app_name == 'customer' && File.exist?(runner_scheme_path)
    preserve_flutter_scheme_configuration(
      runner_scheme_path,
      runner.uuid,
      prepare_framework: true
    )
  end

  project.save
end

puts 'Configured iOS development, staging and production flavors for all apps.'
