#!/usr/bin/env ruby
# frozen_string_literal: true

require 'base64'
require 'fileutils'

begin
  require 'xcodeproj'
rescue LoadError
  # Homebrew CocoaPods keeps its gems in an isolated libexec. Reuse the
  # already-installed xcodeproj there without modifying the host Ruby setup.
  gem_libs = [
    '/opt/homebrew/Cellar/cocoapods/*/libexec/gems/*/lib',
    '/usr/local/Cellar/cocoapods/*/libexec/gems/*/lib'
  ].flat_map { |pattern| Dir[pattern] }
  $LOAD_PATH.unshift(*gem_libs)
  require 'xcodeproj'
end

ROOT = File.expand_path('..', __dir__)
APPS = {
  'customer' => {
    bundle_id: 'net.planext4u.customer',
    display_name: 'Planext4u Customer',
    path_prefix: '/app'
  },
  'vendor' => {
    bundle_id: 'net.planext4u.vendor',
    display_name: 'Planext4u Vendor',
    path_prefix: '/vendor'
  },
  'rider' => {
    bundle_id: 'net.planext4u.rider',
    display_name: 'Planext4u Rider',
    path_prefix: '/rider'
  }
}.freeze
FLAVORS = {
  'development' => {
    identifier_suffix: '.dev',
    display_suffix: ' Dev',
    host: 'dev.planext4u.net',
    scheme_suffix: '-dev'
  },
  'staging' => {
    identifier_suffix: '.staging',
    display_suffix: ' Staging',
    host: 'staging.planext4u.net',
    scheme_suffix: '-staging'
  },
  'production' => {
    identifier_suffix: '',
    display_suffix: '',
    host: 'planext4u.net',
    scheme_suffix: ''
  }
}.freeze
MODES = {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release
}.freeze

def deep_copy(value)
  Marshal.load(Marshal.dump(value))
end

def write_xcconfig(app_dir, app_name, app, flavor_name, flavor, mode)
  base_config = mode == 'Debug' ? 'Debug.xcconfig' : 'Release.xcconfig'
  dart_define = Base64.strict_encode64("APP_ENV=#{flavor_name}")
  contents = <<~CONFIG
    // Generated by tool/configure_ios_flavors.rb. Do not edit by hand.
    #include "#{base_config}"
    APP_ENV = #{flavor_name}
    APP_DISPLAY_NAME = #{app[:display_name]}#{flavor[:display_suffix]}
    PRODUCT_BUNDLE_IDENTIFIER = #{app[:bundle_id]}#{flavor[:identifier_suffix]}
    DEEPLINK_HOST = #{flavor[:host]}
    DEEPLINK_SCHEME = planext4u-#{app_name}#{flavor[:scheme_suffix]}
    DEEPLINK_PATH_PREFIX = #{app[:path_prefix]}
    DART_DEFINES = $(inherited),#{dart_define}
  CONFIG
  path = File.join(app_dir, 'ios', 'Flutter', "#{mode}-#{flavor_name}.xcconfig")
  File.write(path, contents)
end

APPS.each do |app_name, app|
  app_dir = File.join(ROOT, 'apps', app_name)
  project_path = File.join(app_dir, 'ios', 'Runner.xcodeproj')
  project = Xcodeproj::Project.open(project_path)
  runner = project.targets.find { |target| target.name == 'Runner' }
  raise "Runner target missing in #{project_path}" unless runner

  flutter_group = project.main_group.find_subpath('Flutter', true)

  FLAVORS.each do |flavor_name, flavor|
    MODES.each do |mode, type|
      configuration_name = "#{mode}-#{flavor_name}"
      source_project_config = project.build_configurations.find { |config| config.name == mode }
      source_target_config = runner.build_configurations.find { |config| config.name == mode }
      raise "Source #{mode} configuration missing in #{project_path}" unless source_project_config && source_target_config

      write_xcconfig(app_dir, app_name, app, flavor_name, flavor, mode)
      config_filename = "#{configuration_name}.xcconfig"
      file_reference = flutter_group.files.find do |file|
        file.path == config_filename || file.path == "Flutter/#{config_filename}"
      end
      file_reference ||= flutter_group.new_file("Flutter/#{config_filename}")
      file_reference.name = config_filename
      file_reference.path = "Flutter/#{config_filename}"

      project_config = project.add_build_configuration(configuration_name, type)
      project_config.build_settings = deep_copy(source_project_config.build_settings)

      target_config = runner.add_build_configuration(configuration_name, type)
      target_config.build_settings = deep_copy(source_target_config.build_settings)
      target_config.base_configuration_reference = file_reference
      target_config.build_settings['APP_DISPLAY_NAME'] = "#{app[:display_name]}#{flavor[:display_suffix]}"
      target_config.build_settings['CODE_SIGN_ENTITLEMENTS'] = 'Runner/Runner.entitlements'
      target_config.build_settings['DEEPLINK_HOST'] = flavor[:host]
      target_config.build_settings['DEEPLINK_PATH_PREFIX'] = app[:path_prefix]
      target_config.build_settings['DEEPLINK_SCHEME'] = "planext4u-#{app_name}#{flavor[:scheme_suffix]}"
      target_config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = "#{app[:bundle_id]}#{flavor[:identifier_suffix]}"
    end

    scheme = Xcodeproj::XCScheme.new
    scheme.add_build_target(runner)
    scheme.set_launch_target(runner)
    scheme.test_action.build_configuration = 'Debug'
    scheme.launch_action.build_configuration = "Debug-#{flavor_name}"
    scheme.profile_action.build_configuration = "Profile-#{flavor_name}"
    scheme.analyze_action.build_configuration = "Debug-#{flavor_name}"
    scheme.archive_action.build_configuration = "Release-#{flavor_name}"
    scheme.save_as(project_path, flavor_name, true)
  end

  project.save
end

puts 'Configured iOS development, staging and production flavors for all apps.'
