name: planext4u_customer
description: Planext4u customer application.
publish_to: 'none'
version: 0.1.0+1

resolution: workspace

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  planext4u_api_client: ^0.1.0
  planext4u_config: ^0.1.0
  planext4u_core: ^0.1.0
  planext4u_design_system: ^0.1.0
  planext4u_experience: ^0.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
